### ISSUE TITLE
Dark mode for the website

### ISSUE THREAD

**Issue by salmannotkhan** [rstacruz/cheatsheets#1749]
Great website man loved it. thanks for the hard work.

It would be great to have darkmode on website beacuse the plain white background hurts the eyes. also dark reader extension doesn't work for some reason.

**Comment by Kerdek** [comment]
![lightmode](https://user-images.githubusercontent.com/8801228/142773491-b7c26933-beff-477d-ae11-3ffe2f4eca83.png)
Seconded

**Comment by TruncatedDinosour** [comment]
seems to work well with dark reader, maybe it has some CSS that detects what theme you're using? like dark or light? i mean try it or install dark reader 👍

**Comment by salmannotkhan** [comment]
Yes I know sometimes it works but sometimes it just doesn't work at all. It randomly switches to light theme.

**Comment by 0xc0000007b** [comment]
> ![lightmode](https://user-images.githubusercontent.com/8801228/142773491-b7c26933-beff-477d-ae11-3ffe2f4eca83.png) Seconded

LMAO. dude you nailed it. good luck trying to keep a low profile

<img width="1680" alt="Screen Shot 2021-11-28 at 6 35 53 PM" src="https://user-images.githubusercontent.com/94251352/143764417-e6adde77-8921-4c39-91b8-2eea9436d56c.png">

**Comment by Sodj** [comment]
This CSS code is a temporary solution
`filter: invert(.95) hue-rotate(180deg) brightness(125%) contrast(105%);`
Inject it with a browser extension (Stylus, Stylish ... etc)

**Comment by imkarimkarim** [comment]
im up to work on adding a dark mode version. but it seems the project is no longer accepting PRs...

**Comment by TruncatedDinosour** [comment]
> im up to work on adding a dark mode version. but it seems the project is no longer accepting PRs...

i mean 2 years later and dark reader still works soooooooo try it out :)
its nice to have anyway to not burn your eyes

**Comment by imkarimkarim** [comment]
> 

i use and love dark mode. it's really a great extension
the problem is for some browsers you cant install DR(mobile for example) or for some old browsers... a dark mode toggle would be nice.
also, I know most of the users of this site are devs with the last version of the popular browser...

p.s: I'm just looking for something to contribute men... :)

**Comment by imkarimkarim** [comment]
> 

i use and love dark mode. it's really a great extension
the problem is for some browsers you cant install DR(mobile for example) or for some old browsers... a dark mode toggle would be nice.
also, I know most of the users of this site are devs with the last version of the popular browser...

p.s: I'm just looking for something to contribute men... :)

**Comment by imkarimkarim** [comment]
> > im up to work on adding a dark mode version. but it seems the project is no longer accepting PRs...
> 
> i mean 2 years later and dark reader still works soooooooo try it out :) its nice to have anyway to not burn your eyes

i use and love dark mode. it's really a great extension
the problem is for some browsers you cant install DR(mobile for example) or for some old browsers... a dark mode toggle would be nice.
also, I know most of the users of this site are devs with the last version of the popular browser...

p.s: I'm just looking for something to contribute men... :)

**Comment by OiYouYeahYou** [comment]
Hi @rstacruz, Is there anything contributors can do to move this issue forward?

**Comment by TruncatedDinoSour** [comment]
> > > im up to work on adding a dark mode version. but it seems the project is no longer accepting PRs...
> > 
> > 
> > i mean 2 years later and dark reader still works soooooooo try it out :) its nice to have anyway to not burn your eyes
> 
> i use and love dark mode. it's really a great extension the problem is for some browsers you cant install DR(mobile for example) or for some old browsers... a dark mode toggle would be nice. also, I know most of the users of this site are devs with the last version of the popular browser...
> 
> p.s: I'm just looking for something to contribute men... :)

yep i get it, though maybe u should just open a pr, i doubt there needs to b a now 3 year discussion about just adding a dark mode toggle xD

**Comment by salmannotkhan** [comment]
I forgot that I created this issue lol. Maybe it's time to close it.

**Comment by TruncatedDinoSour** [comment]
lmao
